[package]
name = "k-iter"
version = "0.1.0"
authors = ["ROki1988 <roki.swindler@gmail.com>"]

[dependencies]
clap = "2.31.2"
rusoto_core = "0.32.0"
rusoto_kinesis = "0.32.0"
ctrlc = { version = "3.0", features = ["termination"] }
serde = "1.0.39"
serde_derive = "1.0.39"
serde_json = "1.0.15"