[package]
name = "k-iter"
version = "0.4.0"
authors = ["ROki1988 <roki.swindler@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.31.2"
rusoto_core = "0.40.0"
rusoto_kinesis = "0.40.0"
ctrlc = { version = "3.0", features = ["termination"] }
serde = "1.0.2"
serde_derive = "1.0.2"
serde_json = "1.0.1"
bytes = { version = "0.4.12", features = ["serde"] }
futures = "0.1.27"
tokio = "0.2.4"
failure = "0.1.5"